[package]
name = "slint-rust-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.8.0"
rusqlite = {version = "*", features = ["bundled"]}

[build-dependencies]
slint-build = "1.8.0"
