
// app-window.slint
import { MainMenu } from "main-menu.slint";
import { MainApp } from "main-app.slint";

export component AppWindow inherits Window {
    // Shared property for active page
    in-out property <string> active_page: "articles";
    callback menu_clicked(string);
    
    GridLayout {
        spacing: 10px;

        // MainMenu
        MainMenu {
            width: 20%;
            row: 0; col: 0;
            menu_clicked(page_name) => { 
                root.menu_clicked(page_name);
                active_page = page_name;
                }
        }

        // MainApp
        MainApp {
            row: 0; col: 1;
            active_page: active_page;
        }
    }
}

