
// main-menu.slint
import { Button, VerticalBox } from "std-widgets.slint";

export component MainMenu inherits VerticalBox {
    // Declare the callback
    callback menu_clicked(string);

    spacing: 10px;

    Button {
        width: 90%;
        height: 50px;
        text: "Articles";
        clicked => { menu_clicked("articles"); }
    }

    Button {
        width: 90%;
        height: 50px;

        text: "Bills";
        clicked => { menu_clicked("bills"); }
    }

    Button {
        width: 90%;
        height: 50px;

        text: "Customers";
        clicked => { menu_clicked("customers"); }
    }
}


